appConfig:
  release: true
  port: 8080

mysql:
  user: root
  password: 123456
  host: 127.0.0.1
  port: 3306
  db: dbname

log:
  filename: "logs/msg.log"
  maxsize: 100
  maxbackup: 3
  maxage: 28
  compress: true

jwt_secret: "secret"
